version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '0.0.0.0:5432:5432'
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha24
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/dcex_dev
    command:
      - graphql-engine
      - serve
      - --enable-console
volumes:
  ? db_data
